'use strict';

module.exports = {
  async up (queryInterface, Sequelize) {
    return queryInterface.bulkInsert(
      'parts',
      [
        {
          name: 'AMT Sports Air Filter',
          ownerId: 0,
          carId: 0,
          performance: true,
          weight: 1,
          image: 'https://images-na.ssl-images-amazon.com/images/I/81NTICXqCLL.jpg',
          topSpeedEffect: 1,
          accelerationEffect: 2,
          horsePowerEffect: 2,
          brakingEffect: 0,
          handlingEffect: 1,
          stock: 20,
          price: 25,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          name: 'Carbon Winged Spoiler',
          ownerId: 0,
          carId: 0,
          performance: true,
          weight: 10,
          image: 'https://www.spotdem.com/wp-content/uploads/2020/06/spoiler-1024x609.jpg',
          topSpeedEffect: 1,
          accelerationEffect: 0,
          horsePowerEffect: 0,
          brakingEffect: 0,
          handlingEffect: 2,
          stock:  5,
          price: 1500,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          name: 'AMT Stainless Steel Sports Muffler',
          ownerId: 0,
          carId: 0,
          performance: true,
          weight: 25,
          image: 'https://www.swedishcarparts.com/uploads/part_image/file_name/000/001/570/1570/ffcf1156.jpg',
          topSpeedEffect: 0,
          accelerationEffect: 0,
          horsePowerEffect: 3,
          brakingEffect: 0,
          handlingEffect: 0,
          stock: 5,
          price: 2000,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          name: 'Holographic Candy Wrap',
          ownerId: 0,
          carId: 0,
          performance: false,
          weight: 0,
          image: 'https://i.pinimg.com/originals/0c/6c/5e/0c6c5ec856e64b58d7b70738fc98ea29.jpg',
          topSpeedEffect: 0,
          accelerationEffect: 0,
          horsePowerEffect: 0,
          brakingEffect: 0,
          handlingEffect: 0,
          stock: 15,
          price: 15000,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          name: 'Formula 1 High Performance Tires Set (x4)',
          ownerId: 0,
          carId: 0,
          performance: true,
          weight: 88,
          image: 'https://s3-eu-west-1.amazonaws.com/crash.net/image_importer/F1/1523874273.jpg',
          topSpeedEffect: 4,
          accelerationEffect: 2,
          horsePowerEffect: 4,
          brakingEffect: 5,
          handlingEffect: 5,
          stock: 3,
          price: 10000,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          name: 'AIRMEX Front Bumper Lip Chin Bumper Splitter Glossy Kit',
          ownerId: 0,
          carId: 0,
          performance: true,
          weight: 5,
          image: 'https://us-w1-img-listing.eccang.com/0/QjdTYW5WdzNIMmkyaEs1NThFaGdTdz09/202009/5064992TbWjMbXE.jpg',
          topSpeedEffect: 2,
          accelerationEffect: 2,
          horsePowerEffect: 0,
          brakingEffect: 0,
          handlingEffect: -1,
          stock: 10,
          price: 503,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          name: 'Pzero Performance Tires',
          ownerId: 0,
          carId: 0,
          performance: true,
          weight: 10,
          image: 'https://c2.staticflickr.com/2/1600/25893277392_8f16688923_b.jpg',
          topSpeedEffect: 0,
          accelerationEffect: 2,
          horsePowerEffect: 3,
          brakingEffect: 5,
          handlingEffect: 5,
          stock:  10,
          price: 5450,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          name: ' GoodYear BBS Magnesium Racing Rims',
          ownerId: 0,
          carId: 0,
          performance: false,
          weight: 10,
          image: 'https://static.carthrottle.com/workspace/uploads/posts/2017/12/0904c4dd186476687c8732dedb8ba8cc.jpg',
          topSpeedEffect: 0,
          accelerationEffect: 0,
          horsePowerEffect: 0,
          brakingEffect: 0,
          handlingEffect: 0,
          stock:  3,
          price: 1200,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          name: 'Japan JR Racing Rims 17',
          ownerId: 0,
          carId: 0,
          performance: true,
          weight: 20,
          image: 'https://www.jdmdistro.com/wp-content/uploads/2021/02/JR9178582074GD_22279_1.jpg',
          topSpeedEffect: 2,
          accelerationEffect: 1,
          horsePowerEffect: 0,
          brakingEffect: 0,
          handlingEffect: 0,
          stock:  5,
          price: 2500,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          name: 'Nitrous Outlet X-Series Kit',
          ownerId: 0,
          carId: 0,
          performance: true,
          weight: 10,
          image: 'https://static.summitracing.com/global/images/prod/xlarge/nxo-22-90000_zr_xl.jpg',
          topSpeedEffect: 5,
          accelerationEffect: 5,
          horsePowerEffect: 50,
          brakingEffect: 0,
          handlingEffect: 0,
          stock:  5,
          price: 370,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          name: 'Summit Racing™ Extreme Performance Coated Brake Rotors',
          ownerId: 0,
          carId: 0,
          performance: true,
          weight: 15,
          image: 'https://static.summitracing.com/global/images/prod/xlarge/sum-br-62000lc_hf_xl.jpg',
          topSpeedEffect: 0,
          accelerationEffect: 0,
          horsePowerEffect: 0,
          brakingEffect: 3,
          handlingEffect: 2,
          stock:  5,
          price: 70,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          name: 'CalTrend Carbon Fiber Seat Covers',
          ownerId: 0,
          carId: 0,
          performance: false,
          weight: 1,
          image: 'https://static.summitracing.com/global/images/prod/xlarge/cld-carbonfiber_us_xl.jpg',
          topSpeedEffect: 0,
          accelerationEffect: 0,
          horsePowerEffect: 0,
          brakingEffect: 0,
          handlingEffect: 0,
          stock:  5,
          price: 230,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          name: 'Boss BE9ACP Radio System',
          ownerId: 0,
          carId: 0,
          performance: false,
          weight: 3,
          image: 'https://images.crutchfieldonline.com/ImageHandler/trim/750/457/products/2021/30/104/g104BE9ACP-F.jpg',
          topSpeedEffect: 0,
          accelerationEffect: 0,
          horsePowerEffect: 0,
          brakingEffect: 0,
          handlingEffect: 0,
          stock:  5,
          price: 330,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          name: 'Power Stop Performance Brake Calipers',
          ownerId: 0,
          carId: 0,
          performance: true,
          weight: 14,
          image: 'https://b.cdnbrm.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,width=640/https://b.cdnbrm.com/autoanything-website-images/products/large/brakes/power_stop_performance_brake_calipers_hero.jpg',
          topSpeedEffect: 0,
          accelerationEffect: 0,
          horsePowerEffect: 0,
          brakingEffect: 4,
          handlingEffect: 2,
          stock:  5,
          price: 250,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          name: 'APR GTC-300 Adjustable Wing',
          ownerId: 0,
          carId: 0,
          performance: true,
          weight: 25,
          image: 'https://aprperformance.com/wp-content/uploads/2014/09/gtc-300-adjustable-wings_01.jpg',
          topSpeedEffect: 1,
          accelerationEffect: 0,
          horsePowerEffect: 0,
          brakingEffect: 0,
          handlingEffect: 2,
          stock:  3,
          price: 2000,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          name: 'Edelbrock Stage 1 Supercharger Street Kit',
          ownerId: 0,
          carId: 0,
          performance: true,
          weight: 100,
          image: 'https://images.rallysportdirect.com/image/private/s--nvoglqxl--/f_auto,t_manufacturer_image/v1540480737/manufacturer_product_images/k0owqfe8iiiaakrkpepc',
          topSpeedEffect: 10,
          accelerationEffect: 5,
          horsePowerEffect: 10,
          brakingEffect: 0,
          handlingEffect: 0,
          stock:  5,
          price: 6500,
          status: true,
          createdAt: new Date(),
          updatedAt: new Date()
        },
      ]
    )
  },

  async down (queryInterface, Sequelize) {
    return queryInterface.bulkDelete('parts', null, {})
  }
};
